-- ==============================================================================;
-- SALE PAINT — PHASE 2: IDEMPOTENT DATA MIGRATION SEED;
-- Generated At: 2026-09-21T07:40:09.932Z;
-- Strategy: UPSERT with ON CONFLICT (id) DO UPDATE / DO NOTHING;
-- ==============================================================================;

BEGIN;

INSERT INTO public.system_configs (key, value, updated_at, updated_by) VALUES ('google_sheets', '{"spreadsheetId":"","spreadsheetName":"Nippon Paint Sales Main Sheet","webhookUrl":"","autoSync":true,"lastSyncTime":null,"updatedAt":"2026-09-21T07:40:09.929Z","ownerEmail":"ritthiphon.p@nipponpaint.co.th"}'::jsonb, '2026-09-21T07:40:09.932Z', 'system_phase2_migration') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;

INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-01', 'WB-5GL-A-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '5GL', 'A', NULL, 3450, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-02', 'WB-5GL-B-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '5GL', 'B', NULL, 3450, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-03', 'WB-5GL-C-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '5GL', 'C', NULL, 3450, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-04', 'WB-5GL-A-MATT', 'WEATHERBOND', 'ด้าน (Matt)', '5GL', 'A', NULL, 3450, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-05', 'WB-2.5GL-A-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '2.5GL', 'A', NULL, 1850, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-06', 'WB-2.5GL-B-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '2.5GL', 'B', NULL, 1850, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-07', 'WB-1GL-A-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '1GL', 'A', NULL, 780, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wb-08', 'WB-1GL-B-SG', 'WEATHERBOND', 'กึ่งเงา (Semi-Gloss)', '1GL', 'B', NULL, 780, 'NIPPON PAINT', 'สีทาภายนอกพรีเมียม', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-hyb-01', 'HYB-CEIL-5GL-W', 'HYBRID SHIELD สีทาฝ้า', 'ด้านพิเศษลดแสงสะท้อน', '5GL', NULL, 'E777 ขาวสว่างสำหรับฝ้า', 2650, 'NIPPON PAINT', 'สีทาฝ้าเพดาน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-hyb-02', 'HYB-CEIL-5GL-S', 'HYBRID SHIELD สีทาฝ้า', 'ด้านพิเศษลดแสงสะท้อน', '5GL', NULL, 'E888 เทาควันบุหรี่', 2650, 'NIPPON PAINT', 'สีทาฝ้าเพดาน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-hyb-03', 'HYB-CEIL-1GL-W', 'HYBRID SHIELD สีทาฝ้า', 'ด้านพิเศษลดแสงสะท้อน', '1GL', NULL, 'E777 ขาวสว่างสำหรับฝ้า', 590, 'NIPPON PAINT', 'สีทาฝ้าเพดาน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-hyb-04', 'HYB-CEIL-1GL-S', 'HYBRID SHIELD สีทาฝ้า', 'ด้านพิเศษลดแสงสะท้อน', '1GL', NULL, 'E888 เทาควันบุหรี่', 590, 'NIPPON PAINT', 'สีทาฝ้าเพดาน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wba-01', 'WBA-5GL-A-SG', 'WEATHERBOND ADVANCE', 'กึ่งเงา', '5GL', 'A', NULL, 4150, 'NIPPON PAINT', 'สีทาภายนอกสะท้อนความร้อน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wba-02', 'WBA-2.5GL-A-SG', 'WEATHERBOND ADVANCE', 'กึ่งเงา', '2.5GL', 'A', NULL, 2250, 'NIPPON PAINT', 'สีทาภายนอกสะท้อนความร้อน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wba-03', 'WBA-1GL-A-SG', 'WEATHERBOND ADVANCE', 'กึ่งเงา', '1GL', 'A', NULL, 950, 'NIPPON PAINT', 'สีทาภายนอกสะท้อนความร้อน', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wbm-01', 'WBM-5GL-A-SG', 'WEATHERBOND MAX', 'กึ่งเงา (Semi-Gloss)', '5GL', 'A', NULL, 4950, 'NIPPON PAINT', 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-wbm-02', 'WBM-1GL-A-SG', 'WEATHERBOND MAX', 'กึ่งเงา (Semi-Gloss)', '1GL', 'A', NULL, 1150, 'NIPPON PAINT', 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-air-01', 'AIR-5GL-A-DM', 'AIRCARE INTERIOR', 'ด้านพิเศษ (Dead Matt)', '5GL', 'A', NULL, 3890, 'NIPPON PAINT', 'สีทาภายในฟอกอากาศ', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-air-02', 'AIR-2.5GL-A-DM', 'AIRCARE INTERIOR', 'ด้านพิเศษ (Dead Matt)', '2.5GL', 'A', NULL, 2050, 'NIPPON PAINT', 'สีทาภายในฟอกอากาศ', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-air-03', 'AIR-1GL-A-DM', 'AIRCARE INTERIOR', 'ด้านพิเศษ (Dead Matt)', '1GL', 'A', NULL, 890, 'NIPPON PAINT', 'สีทาภายในฟอกอากาศ', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-vin-01', 'VIN-5GL-W', 'VINILEX 5000', 'ด้าน', '5GL', NULL, '100 ขาวเนียน', 2250, 'NIPPON PAINT', 'สีน้ำอะคริลิกคุณภาพสูง', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-vin-02', 'VIN-2.5GL-W', 'VINILEX 5000', 'ด้าน', '2.5GL', NULL, '100 ขาวเนียน', 1180, 'NIPPON PAINT', 'สีน้ำอะคริลิกคุณภาพสูง', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-vin-03', 'VIN-1GL-W', 'VINILEX 5000', 'ด้าน', '1GL', NULL, '100 ขาวเนียน', 490, 'NIPPON PAINT', 'สีน้ำอะคริลิกคุณภาพสูง', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-pri-01', 'PRI-5GL', 'QUICK SEALER PRIMER', 'รองพื้นปูนเก่า-ใหม่', '5GL', NULL, 'ใส / ขาว', 2950, 'NIPPON PAINT', 'สีรองพื้นอเนกประสงค์', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;
INSERT INTO public.catalog_items (id, sku, name, film_color, size, base, color_code, price, brand, category, created_at, updated_at) VALUES ('cat-pri-02', 'PRI-1GL', 'QUICK SEALER PRIMER', 'รองพื้นปูนเก่า-ใหม่', '1GL', NULL, 'ใส / ขาว', 650, 'NIPPON PAINT', 'สีรองพื้นอเนกประสงค์', '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, price = EXCLUDED.price, updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-wb-01', 'WB-EXT-01', 'WEATHERBOND', 'NIPPON PAINT', 'สีทาภายนอกระดับพรีเมียม', '["5GL","2.5GL","1GL"]'::jsonb, true, '["A","B","C","D"]'::jsonb, true, '["กึ่งเงา (Semi-Gloss)","ด้าน (Matt)"]'::jsonb, true, '{"5GL":3450,"2.5GL":1850,"1GL":780,"1/4GL":240}'::jsonb, '{"5GL_A":18,"5GL_B":8,"5GL_C":4,"2.5GL_A":12,"1GL_A":25}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-wba-02', 'WBA-ADV-02', 'WEATHERBOND ADVANCE', 'NIPPON PAINT', 'สีทาภายนอกสะท้อนความร้อน', '["5GL","2.5GL","1GL"]'::jsonb, true, '["A","B","C"]'::jsonb, true, '["กึ่งเงา","เนียน (Sheen)"]'::jsonb, true, '{"5GL":4150,"2.5GL":2250,"1GL":950,"1/4GL":290}'::jsonb, '{"5GL_A":10,"5GL_B":6,"2.5GL_A":14,"1GL_A":15}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-wbm-03', 'WBM-MAX-03', 'WEATHERBOND MAX', 'NIPPON PAINT', 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี', '["5GL","1GL"]'::jsonb, true, '["A","B","C","D"]'::jsonb, true, '["กึ่งเงา (Semi-Gloss)"]'::jsonb, true, '{"5GL":4950,"2.5GL":2600,"1GL":1150,"1/4GL":340}'::jsonb, '{"5GL_A":12,"5GL_B":5,"1GL_A":8}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-air-04', 'AIR-INT-04', 'AIRCARE INTERIOR', 'NIPPON PAINT', 'สีทาภายในฟอกอากาศ ปราศจากสารระเหย', '["5GL","2.5GL","1GL"]'::jsonb, true, '["A","B"]'::jsonb, true, '["ด้านพิเศษ (Dead Matt)","กึ่งเงา"]'::jsonb, true, '{"5GL":3890,"2.5GL":2050,"1GL":890,"1/4GL":260}'::jsonb, '{"5GL_A":20,"2.5GL_A":15,"1GL_A":30}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-vin-05', 'VIN-PRM-05', 'VINILEX 5000', 'NIPPON PAINT', 'สีน้ำอะคริลิกคุณภาพสูง', '["5GL","2.5GL","1GL","1/4GL"]'::jsonb, false, '[]'::jsonb, false, '[]'::jsonb, false, '{"5GL":2250,"2.5GL":1180,"1GL":490,"1/4GL":150}'::jsonb, '{"5GL_A":35,"2.5GL_A":20,"1GL_A":40}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-pri-06', 'PRI-QUICK-06', 'QUICK SEALER PRIMER', 'NIPPON PAINT', 'น้ำยารองพื้นปูนอเนกประสงค์สูตรน้ำมัน', '["5GL","1GL"]'::jsonb, false, '[]'::jsonb, false, '[]'::jsonb, false, '{"5GL":2950,"2.5GL":1600,"1GL":650,"1/4GL":200}'::jsonb, '{"5GL_A":22,"1GL_A":18}'::jsonb, true, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-boa-07', 'BOA-SHIELD-07', 'BODYSGARD ROOF SHIELD', 'NIPPON PAINT', 'สีทาหลังคาและกันซึมดาดฟ้า', '["5GL","1GL"]'::jsonb, true, '["A","B"]'::jsonb, true, '["กึ่งเงา"]'::jsonb, true, '{"5GL":3200,"2.5GL":1750,"1GL":720,"1/4GL":220}'::jsonb, '{"5GL_A":14,"1GL_A":12}'::jsonb, false, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;
INSERT INTO public.products (id, sku, name, brand, category, available_sizes, has_bases, available_bases, has_film_color, film_colors, has_color_code, base_prices, initial_stock, is_quick_pick, created_at, updated_at) VALUES ('prod-wood-08', 'WOOD-STAIN-08', 'TIMBERSHIELD WOOD STAIN', 'NIPPON PAINT', 'สีย้อมไม้ภายนอก ชนิดโปร่งแสง', '["1GL","1/4GL"]'::jsonb, false, '[]'::jsonb, true, '["เงา (Gloss)","ด้าน (Matt)"]'::jsonb, true, '{"5GL":0,"2.5GL":0,"1GL":890,"1/4GL":280}'::jsonb, '{"1GL_A":16,"1/4GL_A":20}'::jsonb, false, '2026-09-21T07:40:09.932Z', '2026-09-21T07:40:09.932Z') ON CONFLICT (id) DO UPDATE SET sku = EXCLUDED.sku, name = EXCLUDED.name, base_prices = EXCLUDED.base_prices, updated_at = EXCLUDED.updated_at;




COMMIT;