import {
  ProductConfig,
  CommissionConfig,
  GallonIncentiveRule,
  BrandSettings,
  MonthTargetData,
  CatalogItem,
} from './types';

export const INITIAL_CATALOG_ITEMS: CatalogItem[] = [
  // WEATHERBOND - มีขนาด เบส และฟิล์มสี
  { id: 'cat-wb-01', sku: 'WB-5GL-A-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '5GL', base: 'A', colorCode: '-', price: 3450, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-02', sku: 'WB-5GL-B-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '5GL', base: 'B', colorCode: '-', price: 3450, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-03', sku: 'WB-5GL-C-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '5GL', base: 'C', colorCode: '-', price: 3450, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-04', sku: 'WB-5GL-A-MATT', name: 'WEATHERBOND', filmColor: 'ด้าน (Matt)', size: '5GL', base: 'A', colorCode: '-', price: 3450, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-05', sku: 'WB-2.5GL-A-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '2.5GL', base: 'A', colorCode: '-', price: 1850, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-06', sku: 'WB-2.5GL-B-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '2.5GL', base: 'B', colorCode: '-', price: 1850, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-07', sku: 'WB-1GL-A-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '1GL', base: 'A', colorCode: '-', price: 780, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },
  { id: 'cat-wb-08', sku: 'WB-1GL-B-SG', name: 'WEATHERBOND', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '1GL', base: 'B', colorCode: '-', price: 780, brand: 'NIPPON PAINT', category: 'สีทาภายนอกพรีเมียม' },

  // HYBRID SHIELD สีทาฝ้าเพดาน - มีเฉพาะขนาดกับเบอร์สี (ไม่มีเบส ไม่ต้องเลือกเบส)
  { id: 'cat-hyb-01', sku: 'HYB-CEIL-5GL-W', name: 'HYBRID SHIELD สีทาฝ้า', filmColor: 'ด้านพิเศษลดแสงสะท้อน', size: '5GL', base: '-', colorCode: 'E777 ขาวสว่างสำหรับฝ้า', price: 2650, brand: 'NIPPON PAINT', category: 'สีทาฝ้าเพดาน' },
  { id: 'cat-hyb-02', sku: 'HYB-CEIL-5GL-S', name: 'HYBRID SHIELD สีทาฝ้า', filmColor: 'ด้านพิเศษลดแสงสะท้อน', size: '5GL', base: '-', colorCode: 'E888 เทาควันบุหรี่', price: 2650, brand: 'NIPPON PAINT', category: 'สีทาฝ้าเพดาน' },
  { id: 'cat-hyb-03', sku: 'HYB-CEIL-1GL-W', name: 'HYBRID SHIELD สีทาฝ้า', filmColor: 'ด้านพิเศษลดแสงสะท้อน', size: '1GL', base: '-', colorCode: 'E777 ขาวสว่างสำหรับฝ้า', price: 590, brand: 'NIPPON PAINT', category: 'สีทาฝ้าเพดาน' },
  { id: 'cat-hyb-04', sku: 'HYB-CEIL-1GL-S', name: 'HYBRID SHIELD สีทาฝ้า', filmColor: 'ด้านพิเศษลดแสงสะท้อน', size: '1GL', base: '-', colorCode: 'E888 เทาควันบุหรี่', price: 590, brand: 'NIPPON PAINT', category: 'สีทาฝ้าเพดาน' },

  // WEATHERBOND ADVANCE
  { id: 'cat-wba-01', sku: 'WBA-5GL-A-SG', name: 'WEATHERBOND ADVANCE', filmColor: 'กึ่งเงา', size: '5GL', base: 'A', colorCode: '-', price: 4150, brand: 'NIPPON PAINT', category: 'สีทาภายนอกสะท้อนความร้อน' },
  { id: 'cat-wba-02', sku: 'WBA-2.5GL-A-SG', name: 'WEATHERBOND ADVANCE', filmColor: 'กึ่งเงา', size: '2.5GL', base: 'A', colorCode: '-', price: 2250, brand: 'NIPPON PAINT', category: 'สีทาภายนอกสะท้อนความร้อน' },
  { id: 'cat-wba-03', sku: 'WBA-1GL-A-SG', name: 'WEATHERBOND ADVANCE', filmColor: 'กึ่งเงา', size: '1GL', base: 'A', colorCode: '-', price: 950, brand: 'NIPPON PAINT', category: 'สีทาภายนอกสะท้อนความร้อน' },

  // WEATHERBOND MAX
  { id: 'cat-wbm-01', sku: 'WBM-5GL-A-SG', name: 'WEATHERBOND MAX', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '5GL', base: 'A', colorCode: '-', price: 4950, brand: 'NIPPON PAINT', category: 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี' },
  { id: 'cat-wbm-02', sku: 'WBM-1GL-A-SG', name: 'WEATHERBOND MAX', filmColor: 'กึ่งเงา (Semi-Gloss)', size: '1GL', base: 'A', colorCode: '-', price: 1150, brand: 'NIPPON PAINT', category: 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี' },

  // AIRCARE INTERIOR
  { id: 'cat-air-01', sku: 'AIR-5GL-A-DM', name: 'AIRCARE INTERIOR', filmColor: 'ด้านพิเศษ (Dead Matt)', size: '5GL', base: 'A', colorCode: '-', price: 3890, brand: 'NIPPON PAINT', category: 'สีทาภายในฟอกอากาศ' },
  { id: 'cat-air-02', sku: 'AIR-2.5GL-A-DM', name: 'AIRCARE INTERIOR', filmColor: 'ด้านพิเศษ (Dead Matt)', size: '2.5GL', base: 'A', colorCode: '-', price: 2050, brand: 'NIPPON PAINT', category: 'สีทาภายในฟอกอากาศ' },
  { id: 'cat-air-03', sku: 'AIR-1GL-A-DM', name: 'AIRCARE INTERIOR', filmColor: 'ด้านพิเศษ (Dead Matt)', size: '1GL', base: 'A', colorCode: '-', price: 890, brand: 'NIPPON PAINT', category: 'สีทาภายในฟอกอากาศ' },

  // VINILEX 5000 - สีทาอาคารสำเร็จรูป
  { id: 'cat-vin-01', sku: 'VIN-5GL-W', name: 'VINILEX 5000', filmColor: 'ด้าน', size: '5GL', base: '-', colorCode: '100 ขาวเนียน', price: 2250, brand: 'NIPPON PAINT', category: 'สีน้ำอะคริลิกคุณภาพสูง' },
  { id: 'cat-vin-02', sku: 'VIN-2.5GL-W', name: 'VINILEX 5000', filmColor: 'ด้าน', size: '2.5GL', base: '-', colorCode: '100 ขาวเนียน', price: 1180, brand: 'NIPPON PAINT', category: 'สีน้ำอะคริลิกคุณภาพสูง' },
  { id: 'cat-vin-03', sku: 'VIN-1GL-W', name: 'VINILEX 5000', filmColor: 'ด้าน', size: '1GL', base: '-', colorCode: '100 ขาวเนียน', price: 490, brand: 'NIPPON PAINT', category: 'สีน้ำอะคริลิกคุณภาพสูง' },

  // QUICK SEALER PRIMER
  { id: 'cat-pri-01', sku: 'PRI-5GL', name: 'QUICK SEALER PRIMER', filmColor: 'รองพื้นปูนเก่า-ใหม่', size: '5GL', base: '-', colorCode: 'ใส / ขาว', price: 2950, brand: 'NIPPON PAINT', category: 'สีรองพื้นอเนกประสงค์' },
  { id: 'cat-pri-02', sku: 'PRI-1GL', name: 'QUICK SEALER PRIMER', filmColor: 'รองพื้นปูนเก่า-ใหม่', size: '1GL', base: '-', colorCode: 'ใส / ขาว', price: 650, brand: 'NIPPON PAINT', category: 'สีรองพื้นอเนกประสงค์' },
];

export const INITIAL_PRODUCTS: ProductConfig[] = [
  {
    id: 'prod-wb-01',
    sku: 'WB-EXT-01',
    name: 'WEATHERBOND',
    brand: 'NIPPON PAINT',
    category: 'สีทาภายนอกระดับพรีเมียม',
    availableSizes: ['5GL', '2.5GL', '1GL'],
    hasBases: true,
    availableBases: ['A', 'B', 'C', 'D'],
    hasFilmColor: true,
    filmColors: ['กึ่งเงา (Semi-Gloss)', 'ด้าน (Matt)'],
    hasColorCode: true,
    basePrices: {
      '5GL': 3450,
      '2.5GL': 1850,
      '1GL': 780,
      '1/4GL': 240,
    },
    initialStock: {
      '5GL_A': 18,
      '5GL_B': 8,
      '5GL_C': 4,
      '2.5GL_A': 12,
      '1GL_A': 25,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-wba-02',
    sku: 'WBA-ADV-02',
    name: 'WEATHERBOND ADVANCE',
    brand: 'NIPPON PAINT',
    category: 'สีทาภายนอกสะท้อนความร้อน',
    availableSizes: ['5GL', '2.5GL', '1GL'],
    hasBases: true,
    availableBases: ['A', 'B', 'C'],
    hasFilmColor: true,
    filmColors: ['กึ่งเงา', 'เนียน (Sheen)'],
    hasColorCode: true,
    basePrices: {
      '5GL': 4150,
      '2.5GL': 2250,
      '1GL': 950,
      '1/4GL': 290,
    },
    initialStock: {
      '5GL_A': 10,
      '5GL_B': 6,
      '2.5GL_A': 14,
      '1GL_A': 15,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-wbm-03',
    sku: 'WBM-MAX-03',
    name: 'WEATHERBOND MAX',
    brand: 'NIPPON PAINT',
    category: 'สีทาภายนอกอัลตร้าพรีเมียม 15 ปี',
    availableSizes: ['5GL', '1GL'],
    hasBases: true,
    availableBases: ['A', 'B', 'C', 'D'],
    hasFilmColor: true,
    filmColors: ['กึ่งเงา (Semi-Gloss)'],
    hasColorCode: true,
    basePrices: {
      '5GL': 4950,
      '2.5GL': 2600,
      '1GL': 1150,
      '1/4GL': 340,
    },
    initialStock: {
      '5GL_A': 12,
      '5GL_B': 5,
      '1GL_A': 8,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-air-04',
    sku: 'AIR-INT-04',
    name: 'AIRCARE INTERIOR',
    brand: 'NIPPON PAINT',
    category: 'สีทาภายในฟอกอากาศ ปราศจากสารระเหย',
    availableSizes: ['5GL', '2.5GL', '1GL'],
    hasBases: true,
    availableBases: ['A', 'B'],
    hasFilmColor: true,
    filmColors: ['ด้านพิเศษ (Dead Matt)', 'กึ่งเงา'],
    hasColorCode: true,
    basePrices: {
      '5GL': 3890,
      '2.5GL': 2050,
      '1GL': 890,
      '1/4GL': 260,
    },
    initialStock: {
      '5GL_A': 20,
      '2.5GL_A': 15,
      '1GL_A': 30,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-vin-05',
    sku: 'VIN-PRM-05',
    name: 'VINILEX 5000',
    brand: 'NIPPON PAINT',
    category: 'สีน้ำอะคริลิกคุณภาพสูง',
    availableSizes: ['5GL', '2.5GL', '1GL', '1/4GL'],
    hasBases: false,
    hasFilmColor: false,
    hasColorCode: false,
    basePrices: {
      '5GL': 2250,
      '2.5GL': 1180,
      '1GL': 490,
      '1/4GL': 150,
    },
    initialStock: {
      '5GL_A': 35,
      '2.5GL_A': 20,
      '1GL_A': 40,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-pri-06',
    sku: 'PRI-QUICK-06',
    name: 'QUICK SEALER PRIMER',
    brand: 'NIPPON PAINT',
    category: 'น้ำยารองพื้นปูนอเนกประสงค์สูตรน้ำมัน',
    availableSizes: ['5GL', '1GL'],
    hasBases: false,
    hasFilmColor: false,
    hasColorCode: false,
    basePrices: {
      '5GL': 2950,
      '2.5GL': 1600,
      '1GL': 650,
      '1/4GL': 200,
    },
    initialStock: {
      '5GL_A': 22,
      '1GL_A': 18,
    },
    isQuickPick: true,
  },
  {
    id: 'prod-boa-07',
    sku: 'BOA-SHIELD-07',
    name: 'BODYSGARD ROOF SHIELD',
    brand: 'NIPPON PAINT',
    category: 'สีทาหลังคาและกันซึมดาดฟ้า',
    availableSizes: ['5GL', '1GL'],
    hasBases: true,
    availableBases: ['A', 'B'],
    hasFilmColor: true,
    filmColors: ['กึ่งเงา'],
    hasColorCode: true,
    basePrices: {
      '5GL': 3200,
      '2.5GL': 1750,
      '1GL': 720,
      '1/4GL': 220,
    },
    initialStock: {
      '5GL_A': 14,
      '1GL_A': 12,
    },
    isQuickPick: false,
  },
  {
    id: 'prod-wood-08',
    sku: 'WOOD-STAIN-08',
    name: 'TIMBERSHIELD WOOD STAIN',
    brand: 'NIPPON PAINT',
    category: 'สีย้อมไม้ภายนอก ชนิดโปร่งแสง',
    availableSizes: ['1GL', '1/4GL'],
    hasBases: false,
    hasFilmColor: true,
    filmColors: ['เงา (Gloss)', 'ด้าน (Matt)'],
    hasColorCode: true,
    basePrices: {
      '5GL': 0,
      '2.5GL': 0,
      '1GL': 890,
      '1/4GL': 280,
    },
    initialStock: {
      '1GL_A': 16,
      '1/4GL_A': 20,
    },
    isQuickPick: false,
  }
];

export const INITIAL_BRAND_SETTINGS: BrandSettings = {
  brandName: 'NIPPON PRO SALES',
  subtitle: 'ระบบบริหารงานขายสีและเคลือบผิวครบวงจร',
  branch: 'ศูนย์ตัวแทนจำหน่ายหลัก สาขากรุงเทพฯ ตะวันออก',
  badge: 'OFFICIAL PRO DEALER',
  theme: 'red',
  lineOaUrl: 'https://line.me/ti/p/@paintpro',
};

export const INITIAL_COMMISSION_CONFIG: CommissionConfig = {
  monthlyTarget: 500000,
  headcount: 3,
  tiers: [
    { achievementPercent: 80, rewardAmount: 3000 },
    { achievementPercent: 85, rewardAmount: 4500 },
    { achievementPercent: 90, rewardAmount: 6000 },
    { achievementPercent: 95, rewardAmount: 8000 },
    { achievementPercent: 100, rewardAmount: 12000 },
    { achievementPercent: 105, rewardAmount: 15000 },
    { achievementPercent: 110, rewardAmount: 18000 },
    { achievementPercent: 115, rewardAmount: 22000 },
    { achievementPercent: 120, rewardAmount: 27000 },
    { achievementPercent: 125, rewardAmount: 32000 },
    { achievementPercent: 130, rewardAmount: 38000 },
  ],
  specialBands: [
    { id: 'sb-1', minSales: 200000, maxSales: 400000, rewardAmount: 2500 },
    { id: 'sb-2', minSales: 400001, maxSales: 600000, rewardAmount: 5000 },
    { id: 'sb-3', minSales: 600001, maxSales: 1000000, rewardAmount: 10000 },
  ],
  rewardPerHead: 1500,
  requireTargetAchievementForGallon: true,
  minTargetAchievementForGallon: 80, // ต้องทำยอดรวมให้ถึง 80% ของเป้าถึงจะได้รับเงินรายแกนลอน
};

export const INITIAL_GALLON_RULES: GallonIncentiveRule[] = [
  {
    id: 'gr-wb-25gl-a',
    name: 'WEATHERBOND 2.5 GL เบส A จ่ายถังละ 50 บาท',
    ruleType: 'per_unit',
    productName: 'WEATHERBOND',
    selectedSizes: ['2.5GL'],
    selectedBases: ['A'],
    reward: 50,
    enabled: true,
    notes: 'ใช้เกณฑ์รวมระบบ (ต้องได้ยอดขายรวม ≥80% ของเป้า)',
  },
  {
    id: 'gr-wb-bundle-4',
    name: 'WEATHERBOND ขนาด 5GL / 2.5GL เบส A, B รวม 4 ถัง จ่าย 200 บาท',
    ruleType: 'lump_sum_qty',
    productName: 'WEATHERBOND',
    selectedSizes: ['5GL', '2.5GL'],
    selectedBases: ['A', 'B'],
    minQuantity: 4,
    reward: 200,
    minTargetAchievementPercent: 85, // เงื่อนไขเฉพาะ: ต้องทำยอดรวมได้ 85% ของเป้า
    enabled: true,
    notes: 'ขายรวมครบทุกๆ 4 ถัง จ่ายเงินพิเศษ 200 บาท (ต้องได้ยอดรวม ≥85% ของเป้า)',
  },
  {
    id: 'gr-hybrid-ceiling-rev',
    name: 'HYBRID SHIELD สีทาฝ้า ยอดครบ 200,000 บาท จ่ายถังละ 50 บาท',
    ruleType: 'threshold_revenue_per_bucket',
    productName: 'HYBRID SHIELD สีทาฝ้า',
    selectedSizes: ['5GL', '1GL'],
    selectedColorCodes: ['E777 ขาวสว่างสำหรับฝ้า', 'E888 เทาควันบุหรี่'],
    minRevenue: 200000,
    reward: 50,
    minTargetAchievementPercent: 90, // ต้องได้ยอดรวม 90% ของเป้า
    enabled: true,
    notes: 'เมื่อยอดขายรวมของสีทาฝ้าถึง 200,000 บาท จ่ายโบนัสถังละ 50 บาท (ต้องได้ยอดรวม ≥90% ของเป้า)',
  },
  {
    id: 'gr-wb-max',
    name: 'WEATHERBOND MAX ถังใหญ่ 5GL โบนัสถังละ 80 บาท (จ่ายทันที)',
    ruleType: 'per_unit',
    productName: 'WEATHERBOND MAX',
    selectedSizes: ['5GL'],
    reward: 80,
    minTargetAchievementPercent: 0, // 0 = จ่ายทันที ไม่มีเงื่อนไขยอดรวม
    enabled: true,
    notes: 'สีอัลตร้าพรีเมียม จ่ายพิเศษทันทีไม่มีเงื่อนไขยอดรวม',
  },
];

export const INITIAL_YEAR_TARGETS: MonthTargetData[] = [
  { month: 1, year: 2026, target: 450000 },
  { month: 2, year: 2026, target: 480000 },
  { month: 3, year: 2026, target: 520000 },
  { month: 4, year: 2026, target: 490000 },
  { month: 5, year: 2026, target: 510000 },
  { month: 6, year: 2026, target: 530000 },
  { month: 7, year: 2026, target: 500000 },
  { month: 8, year: 2026, target: 520000 },
  { month: 9, year: 2026, target: 550000 },
  { month: 10, year: 2026, target: 580000 },
  { month: 11, year: 2026, target: 600000 },
  { month: 12, year: 2026, target: 650000 },
];
